### ISSUE TITLE
ByAll and ByChained locators always fail with Cannot find element object

### ISSUE THREAD

**Issue by Crydust** [SeleniumHQ/htmlunit-driver#115]
When using a `ByAll` or `ByChained` locator I always get `java.lang.RuntimeException: Cannot find element object`.
It looks like `org.openqa.selenium.htmlunit.ElementConverter#getConverter` tries to convert these locators to something else and fails to do so.

These are the dependencies I use:
```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.1.0</version>
</dependency>
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>htmlunit-driver</artifactId>
    <version>3.56.0</version>
</dependency>
```

Both of these tests fail:
```
package demo;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.support.pagefactory.ByAll;
import org.openqa.selenium.support.pagefactory.ByChained;

class DummyTest {
    @Test
    void shouldSupportByAll() {
        HtmlUnitDriver driver = new HtmlUnitDriver();
        driver.get("https://example.com");
        driver.findElement(new ByAll(By.tagName("div"), By.tagName("h1")));
    }
    @Test
    void shouldSupportByChained() {
        HtmlUnitDriver driver = new HtmlUnitDriver();
        driver.get("https://example.com");
        driver.findElement(new ByChained(By.tagName("div"), By.tagName("h1")));
    }
}
```

Stacktrace:
```
java.lang.RuntimeException: Cannot find element object

	at org.openqa.selenium.htmlunit.ElementConverter.lambda$getConverter$1(ElementConverter.java:147)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.openqa.selenium.htmlunit.ElementConverter.getConverter(ElementConverter.java:147)
	at org.openqa.selenium.htmlunit.ElementConverter.access$000(ElementConverter.java:47)
	at org.openqa.selenium.htmlunit.ElementConverter$HtmlUnitElementConverter.getElementObject(ElementConverter.java:80)
	at org.openqa.selenium.htmlunit.HtmlUnitElementFinder.findElement(HtmlUnitElementFinder.java:47)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$findElement$8(HtmlUnitDriver.java:633)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.implicitlyWaitFor(HtmlUnitDriver.java:1056)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:633)
	at demo.DummyTest.shouldSupportByChained(DummyTest.java:20)
```

This workaround works for me, but will not work for nested ByChained and ByAll locators.
```
package demo;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.support.pagefactory.ByAll;
import org.openqa.selenium.support.pagefactory.ByChained;

class DummyTest {
	@Test
	void shouldSupportByAll() {
		HtmlUnitDriver driver = new HtmlUnitDriver();
		driver.get("https://example.com");
		new ByAll(By.tagName("div"), By.tagName("h1")).findElements(driver);
	}
	@Test
	void shouldSupportByChained() {
		HtmlUnitDriver driver = new HtmlUnitDriver();
		driver.get("https://example.com");
		new ByChained(By.tagName("div"), By.tagName("h1")).findElements(driver);
	}
}

```

**Comment by rbri** [comment]
fixed in the last release - many thanks for reporting this.
