### ISSUE TITLE
HtmlUnit driver w/ Selenium 3.0.0-beta3

### ISSUE THREAD

**Issue by filipcynarski** [SeleniumHQ/htmlunit-driver#25]
Hello,

I'm trying to run my unit tests w/ project which wraps Selenium 3.0.0-beta3 I'm facing following issue:

This is for HtmlUnit driver 2.23

```
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/api/Session
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.process(AbstractJavaScriptConfiguration.java:197)
	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.getClassConfiguration(AbstractJavaScriptConfiguration.java:172)
	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.buildUsageMap(AbstractJavaScriptConfiguration.java:79)
	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.<init>(AbstractJavaScriptConfiguration.java:59)
	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.<init>(JavaScriptConfiguration.java:597)
	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.getInstance(JavaScriptConfiguration.java:613)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.<init>(JavaScriptEngine.java:133)
	at com.gargoylesoftware.htmlunit.WebClient.init(WebClient.java:239)
	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:213)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.newWebClient(HtmlUnitDriver.java:349)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.createWebClient(HtmlUnitDriver.java:315)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.<init>(HtmlUnitDriver.java:192)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.<init>(HtmlUnitDriver.java:249)
	... 40 more
```

When I downgrade to lastly released HtmlUnit driver I'm getting different error because of Selenium implementation changed.

This is for HtmlUnit driver 2.21

```
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/SessionNotFoundException
```

So it seems the HtmlUnit driver 2.23 should be better but I can't figure out why it is asking for Jetty dependency.

**Comment by filipcynarski** [comment]
Issue resolved I've added dependencies to:

```
<dependency>
            <groupId>org.eclipse.jetty.websocket</groupId>
            <artifactId>websocket-api</artifactId>
            <version>9.3.5.v20151012</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty.websocket</groupId>
            <artifactId>websocket-client</artifactId>
            <version>9.3.5.v20151012</version>
        </dependency>
```
