### ISSUE TITLE
AbstractMethodError: HtmlUnitWebElement.getCoordinates()

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/htmlunit-driver#74]
@asolntsev commented on [Sat Nov 03 2018](https://github.com/SeleniumHQ/selenium/issues/6612)

## Meta -
OS:  MacOS
Selenium Version:  3.141.0
Browser: HtmlUnit
Browser Version: 2.33
HtmlUnitDriver Version: 2.33.0

## Steps to reproduce -

```java
HtmlUnitDriver driver = new HtmlUnitDriver(...);
WebElement element = driver.findElement(...);
new Actions(driver).doubleClick(element).perform();
```

## Result:
I am getting technical error:

```java
java.lang.AbstractMethodError: org.openqa.selenium.htmlunit.HtmlUnitWebElement.getCoordinates()Lorg/openqa/selenium/interactions/Coordinates;
	at org.openqa.selenium.interactions.internal.MouseAction.getActionLocation(MouseAction.java:69)
	at org.openqa.selenium.interactions.internal.MouseAction.moveToLocation(MouseAction.java:76)
	at org.openqa.selenium.interactions.DoubleClickAction.perform(DoubleClickAction.java:42)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:34)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:642)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:595)
```

---

@cgoldberg commented on [Sat Nov 03 2018](https://github.com/SeleniumHQ/selenium/issues/6612#issuecomment-435596482)

What's the expected result?
Your repro steps attempt to find elements and create Actions, but you never navigated to a page.

**Comment by rbri** [comment]
Please use HtmlUnit driver version 2.33.1 as this version is compiled against 3.141.0.

You can find the version on maven and at https://github.com/SeleniumHQ/htmlunit-driver/releases.

Please report if this solves the issue for you.

**Comment by asolntsev** [comment]
@rbri Thank you! Upgrade to htmlunitdriver 2.33.1 helped.
