### ISSUE TITLE
jira login element not found

### ISSUE THREAD

**Issue by Kitter** [SeleniumHQ/htmlunit-driver#78]
When  I use htmlunit-driver to test jira's login, NoSuchElementException error occured.
code:

      WebDriver` driver = new HtmlUnitDriver();
      driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
      driver.get("http://xxx.xxx.xxx.xxx:8080/secure/Dashboard.jspa");
      driver.findElement(By.id("login-form-username")).sendKeys("XXXXXX");
      driver.findElement(By.id("login-form-password")).sendKeys("XXXXXX");
      driver.findElement(By.id("login-form-username")).click();

error info:

     Exception in thread "main" org.openqa.selenium.NoSuchElementException: Unable to locate element 
     with ID: 'login-form-username'
     For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
     Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
     System info: host: 'XXXX, ip: 'xxx.xxx.xxx.xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_172'
    Driver info: driver.version: HtmlUnitDriver
            at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementById(HtmlUnitDriver.java:1256)
            at org.openqa.selenium.By$ById.findElement(By.java:188)
            at org.openqa.selenium.htmlunit.HtmlUnitDriver$4.call(HtmlUnitDriver.java:2030)
            at org.openqa.selenium.htmlunit.HtmlUnitDriver$4.call(HtmlUnitDriver.java:2026)
            at org.openqa.selenium.htmlunit.HtmlUnitDriver.implicitlyWaitFor(HtmlUnitDriver.java:1661)
            at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:2026)
            at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:799)
            at Test1.main(Test1.java:21)

Who can help me,thanks.

**Comment by Kitter** [comment]
I change “WebDriver` driver = new HtmlUnitDriver();“ to “WebDriver` driver = new HtmlUnitDriver(true);”，error does not appear.
