### ISSUE TITLE
Unable to run tests using HtmlUnitDriver

### ISSUE THREAD

**Issue by gajananrmahajan** [SeleniumHQ/htmlunit-driver#84]
In order to run tests using `HtmlUnitDriver`, I added latest maven dependency in `pom.xml`

    
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>htmlunit-driver</artifactId>
        <version>2.36.0</version>
    </dependency>

 and has following code -

        @Test
        public void test() {
    
            WebDriver driver = new HtmlUnitDriver();
            driver.manage().window().maximize();

            driver.get("http://www.google.com");
           
            System.out.println("Title is " + driver.getTitle());
    
            driver.quit();
        }

When I run the test, it fails with following  -

    org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'DT01070415', ip: '192.168.41.104', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
    Driver info: driver.version: HtmlUnitDriver
    
    	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:733)
    	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$get$8(HtmlUnitDriver.java:697)
    	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$runAsync$0(HtmlUnitDriver.java:438)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.net.SocketException: Connection reset
    	at java.net.SocketInputStream.read(SocketInputStream.java:210)
    	at java.net.SocketInputStream.read(SocketInputStream.java:141)
    	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
    	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
    	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
    	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
    	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
    	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
    	at com.gargoylesoftware.htmlunit.httpclient.HtmlUnitSSLConnectionSocketFactory.connectSocket(HtmlUnitSSLConnectionSocketFactory.java:184)
    	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
    	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
    	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
    	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
    	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
    	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
    	at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:189)
    	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1407)
    	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1465)
    	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1326)
    	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:396)
    	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:317)
    	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:715)
    	... 5 more

**Comment by sbabcoc** [comment]
Try updating to the latest Selenium 3 HtmlUnitDriver (2.70.0)
