### ISSUE TITLE
htmlunit driver 2.37.0: ArrayIndexOutOfBoundsException while starting up...

### ISSUE THREAD

**Issue by zniff** [SeleniumHQ/htmlunit-driver#85]
Hi everybody

I just switched in my pom.xml from htmlunit.driver 2.36.0 to 2.37.0 (along with selenium-java 3.141.59) and just by upgrading to 2.37.0 i fall into following exception (and switching back to 2.36.0 resolves the problem, i.e. the code runs again): 

```
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 2048
        at 
net.sourceforge.htmlunit.cyberneko.HTMLScanner$CurrentEntity.read(HTMLScanner.java:1901)
        at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:3075)
        at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:2900)
        at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanStartElement(HTMLScanner.java:2747)
        at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2127)
        at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:937)
        at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:443)
        at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:394)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:758)
        at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:236)
        at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parseHtml(HtmlUnitNekoHtmlParser.java:179)
        at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:280)
        at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:163)
        at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:553)
        at com.gargoylesoftware.htmlunit.WebClient.loadDownloadedResponses(WebClient.java:2308)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.doProcessPostponedActions(JavaScriptEngine.java:913)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.processPostponedActions(JavaScriptEngine.java:1002)
        at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:1059)
        at com.gargoylesoftware.htmlunit.html.HtmlAnchor.click(HtmlAnchor.java:85)
        at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:990)
        at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:896)
        at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:877)
        at org.openqa.selenium.htmlunit.HtmlUnitMouse.click(HtmlUnitMouse.java:84)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$click$1(HtmlUnitDriver.java:463)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$runAsync$0(HtmlUnitDriver.java:438)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)

```

It looks like this exception occurrs before or while to load the initial page.
Everything is running on Java 13.0.2 on a Windows 10 machine.

best regards
Erich

**Comment by rbri** [comment]
Hi Erich,

sorry for that. Looks like a problem introduced with my last Neko fix.
There was already an report about that, please swithch to the latest neko snapshot build (2.38.0-SNAPSHOT) will hopefully fix that.

	RBRi

On Sun, 02 Feb 2020 06:28:30 -0800 Erich Siffert wrote:
>
>Hi everybody
>
>I just switched in my pom.xml from htmlunit.driver 2.36.0 to 2.37.0 (along with selenium-java 3.141.59) and just by upgrading to 2.37.0 i fall into following 
exception (and switching back to 2.36.0 resolves the problem, i.e. the code runs again): 
>
>```
>java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 2048
>        at 
>net.sourceforge.htmlunit.cyberneko.HTMLScanner$CurrentEntity.read(HTMLScanner.java:1901)
>        at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:3075)
>        at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:2900)
>        at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanStartElement(HTMLScanner.java:2747)
>        at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2127)
>        at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:937)
>        at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:443)
>        at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:394)
>        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
>        at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:758)
>        at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:236)
>        at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parseHtml(HtmlUnitNekoHtmlParser.java:179)
>        at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:280)
>        at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:163)
>        at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:553)
>        at com.gargoylesoftware.htmlunit.WebClient.loadDownloadedResponses(WebClient.java:2308)
>        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.doProcessPostponedActions(JavaScriptEngine.java:913)
>        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.processPostponedActions(JavaScriptEngine.java:1002)
>        at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:1059)
>        at com.gargoylesoftware.htmlunit.html.HtmlAnchor.click(HtmlAnchor.java:85)
>        at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:990)
>        at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:896)
>        at com.gargoylesoftware.htmlunit.html.DomElement.click(DomElement.java:877)
>        at org.openqa.selenium.htmlunit.HtmlUnitMouse.click(HtmlUnitMouse.java:84)
>        at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$click$1(HtmlUnitDriver.java:463)
>        at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$runAsync$0(HtmlUnitDriver.java:438)
>        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>        at java.base/java.lang.Thread.run(Thread.java:830)
>
>```
>
>It looks like this exception occurrs before or while to load the initial page.
>Everything is running on Java 13.0.2 on an Windows 10 machine.
>
>best regards
>Erich
>
>

**Comment by rbri** [comment]
Btw you can 'follow' the development process here https://twitter.com/HtmlUnit

**Comment by zniff** [comment]
Ah, cool! Thx!

**Comment by rbri** [comment]
Can i close this?

**Comment by zniff** [comment]
Sure! Just closed it....
